<?php echo $this->escapeHtml($this->getMethod()->getTitle())."<br>"; ?>
<?php if($this->getInfo()->getAdditionalData()): ?>
	<?php $additionalData = unserialize( $this->getInfo()->getAdditionalData() ); ?>
	<?php if( isset( $additionalData["source_type"] ) && !empty($additionalData["source_type"]) ): ?>
		<div>
			<?php echo "Type : ".$additionalData["source_type"]; ?>
		</div>
    <?php endif; ?>
    <?php if( isset( $additionalData["source_card_type"] ) && !empty($additionalData["source_card_type"]) ): ?>
		<div>
			<?php echo "Card type : ".$additionalData["source_card_type"]; ?>
		</div>
    <?php endif; ?>
    <?php if( isset( $additionalData["source_exp_date"] ) && !empty($additionalData["source_exp_date"]) ): ?>
		<div>
			<?php echo "Exp date : ".$additionalData["source_exp_date"]; ?>
		</div>
    <?php endif; ?>
    <?php if( isset( $additionalData["source_masked_card"] ) && !empty($additionalData["source_masked_card"]) ): ?>
		<div>
			<?php echo "Masked card : ".$additionalData["source_masked_card"]; ?>
		</div>
    <?php endif; ?>
    <?php if( isset( $additionalData["state"] ) ): ?>
		<div>
			<?php echo "State : ".$additionalData["state"]; ?>
		</div>
	<?php endif; ?>
<?php endif; ?>