<?php echo $this->escapeHtml($this->getMethod()->getTitle())."<br>"; ?>
<?php if($this->getInfo()->getAdditionalData()): ?>
	<?php $additionalData = unserialize( $this->getInfo()->getAdditionalData() ); ?>
	<?php if($additionalData["source_card_type"]): ?>
		<div>
			<?php echo "Card type : ".$additionalData["source_card_type"]; ?>
		</div>
	<?php endif; ?>
	<?php if($additionalData["source_masked_card"]): ?>
		<div>
			<?php echo "Card : ".$additionalData["source_masked_card"]; ?>
		</div>
	<?php endif; ?>
	<?php if($additionalData["source_exp_date"]): ?>
		<div>
			<?php echo "Exp date : ".$additionalData["source_exp_date"]; ?>
		</div>
	<?php endif; ?>
	<?php if($additionalData["card_token"]): ?>
		<div>
			<?php echo "Card token : ".$additionalData["card_token"]; ?>
		</div>
	<?php endif; ?>
	<?php if($additionalData["state"]): ?>
		<div>
			<?php echo "State : ".$additionalData["state"]; ?>
		</div>
	<?php endif; ?>
	<?php if($additionalData["error"]): ?>
		<div>
			<?php echo "Error code : ".$additionalData["error"]; ?>
		</div>
	<?php endif; ?>
	<?php if($additionalData["error_state"]): ?>
		<div>
			<?php echo "Error state : ".$additionalData["error_state"]; ?>
		</div>
	<?php endif; ?>
<?php endif; ?>