<?php 
	$session = Mage::getSingleton('checkout/session');
	$order = Mage::getModel('sales/order')->loadByIncrementId($session->getReepayOrderIncrementId());
?>
<div class="reepay-payment-layout">
	<div class="logo-wrapper">
		<img class="logo" src="<?php echo $this->getSkinUrl(Mage::getStoreConfig('design/header/logo_src')); ?>">
	</div>
	<script type="text/javascript">
		var rp = new Reepay.WindowCheckout('<?php echo $this->getPaymentSessionId(); ?>');
	</script>
</div>